language: objective-c
osx_image: xcode10.2
cache: cocoapods
before_install:
    - gem install cocoapods
    - pod repo update
    - pod install
script:
    - xcodebuild clean test -workspace swiftUV.xcworkspace -scheme swiftUV -destination "platform=iOS Simulator,name=iPhone X,OS=12.2" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
