language: objective-c
osx_image: xcode9.1
before_install:
    - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
    - pod install
script:
    - xcodebuild clean test -workspace swiftUV.xcworkspace -scheme swiftUV -destination "platform=iOS Simulator,name=iPhone 7,OS=11.1" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
